### ISSUE TITLE
Unable to run individual test from CLI

### ISSUE THREAD

**Issue by tomalec** [Starcounter/UniformDocs#375]
### Steps to reproduce
Follow steps from https://github.com/Starcounter/UniformDocs/blob/master/CONTRIBUTING.md#run-the-test-from-command-line

### Expected result
The test results are shown

### Actual result
```
ScErrUnexpectedResponse (SCERR6080): An internal node call returned an unexpected response. 401: HTTP/1.1 401 Unauthorized
Cache-Control: no-store
Date: Thu, 20 Sep 2018 08:24:11 GMT
Server: Starcounter/2.4.990.127
Server: (Windows)
Content-Length: 13

Unauthorized.

Version: 0.0.0.
Help page: https://docs.starcounter.io/?q=SCERR6080.

Type "star -h" or "staradmin -h" to see help

Stack trace:
   at Starcounter.Rest.ExtensionMethods.ResponseExtensions.DefaultErrorHandler(Response response) in C:\tc_work\sc-19252\Level1\src\Starcounter.Internal\Http\ResponseExtensions.cs:line 71
   at Starcounter.Rest.ExtensionMethods.ResponseExtensions.FailIfNotSuccess(Response response) in C:\tc_work\sc-19252\Level1\src\Starcounter.Internal\Http\ResponseExtensions.cs:line 46
   at Starcounter.CLI.StopDatabaseCLICommand.Run() in C:\tc_work\sc-19252\Level1\src\Server\Starcounter.CLI\StopDatabaseCLICommand.cs:line 86
UniformDocs -> default (restarting default .)
```

##### Starcounter version 2.4.0.990.127

Running `test.bat` to test all works fine, but takes long time.
I also have problems with running Selenium with `-enablePassThrough false`:
```
$ java -jar selenium-server-standalone-3.*.jar -enablePassThrough false
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-enablePassThrough' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at org.openqa.grid.internal.cli.StandaloneCliOptions.parse(StandaloneCliOptions.java:28)
        at org.openqa.grid.selenium.GridLauncherV3$1.<init>(GridLauncherV3.java:257)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$0(GridLauncherV3.java:256)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:164)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:98)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:82)
```

**Comment by warpech** [comment]
This is not a problem in UniformDocs but with Starcounter: https://github.com/Starcounter/level1/issues/4699

`staradmin kill all` can help.

If you confirm, please close.
