### ISSUE TITLE
Implement fully parallelizable testing

### ISSUE THREAD

**Issue by warpech** [Starcounter/UniformDocs#396]
Right now, the tests in UniformDocs (and Blending, etc) are not parallelizable. I think that in case of UniformDocs, this is because of one problem:

1. Some tests work on data that is commited to the db

I was thinking that if we could change the code so that the tested pages would use long-running transactions and never commit then we could have fully parallelizable tests.

@kegor could you please give it a try? Please don't spend on it more than a day.

**Comment by warpech** [comment]
In BrowserStack, the queue size is 5, so you can't just push all tests at once to the queue. However, you can retry to put the test in a queue if it was rejected.

There is a REST API method that can return the size of the queue: https://www.browserstack.com/automate/rest-api (edited)

**Comment by kegor** [comment]
I would like to discuss few point which i found during the debugging the possible solutions:
1. On the https://automate.browserstack.com i see that the minimum time of test execution is ~15 sec (Chrome 69.0, Win 10: UniformDocs.Tests.Test.CardPageTest). The longest time that i saw is ~2m 30.
2. Following request: `curl -u "marcinwarpechows2:xAaCqzP1xxjpNsN6b6AM" https://api.browserstack.com/automate/plan.json` returns JSON object:
```
{"automate_plan":"Automate Pro","parallel_sessions_running":0,"team_parallel_sessions_max_allowed":2,"parallel_sessions_max_allowed":2,"queued_sessions":0,"queued_sessions_max_allowed":5}
```
I wrote simple method to be possible analyze these values during the tests running. Probably significant note here from the `BrowserStack` docs:
>**Note:** You can make up to 800 API requests per 5 minutes per user.
3. During attempts to use `Threading.Timer` class for waiting while `parallel_sessions_running` becomes `<2` (or `queued_sessions <4`) i found probably obvious thing that each test class running in the separate thread, and, in my understanding, if we would like to wait while one of 2 available parallel threads on `BrowserStack` (according to the current plan) will be free then we should block all these threads and wait significant amount of time while all tests in one class will be executed.

@warpech, @PatrykSzwer maybe you have more clear picture in your mind how this should work and you can share here?

**Comment by warpech** [comment]
I discussed on Slack with @kegor that I think point 2 can be omitted if he just tries to create a RemoteWebDriver session and then, in case of `System.InvalidOperationException : All parallel tests are currently in use, including the queued tests. Please wait to finish or upgrade your plan to add more sessions.`, puts an attempt to retry into a queue on our side.

**Comment by kegor** [comment]
During further investigation i found the way how some of the tests can be run programmatically in the case were line `Driver = WebDriverManager.StartDriver(_browser, Config.Timeout, serverUri);` (https://github.com/Starcounter/UniformDocs/blob/master/test/UniformDocs.Tests/Test/BaseTest.cs#L52) leads to `OpenQA.Selenium.WebDriverException`:
https://stackoverflow.com/a/17237919/1362723.

I planned to use this method for trying re-run some of the tests taking them from the **queue** (in theory tests were added in this queue in the case of catching exception mentioned above). But seems like mentioned there `nunit.core.dll` & `nunit.core.interfaces.dll` available only for NUnit 2.6.4 and during using with the NUnit 3.11.0 i see the error:
```
11) Error : UniformDocs.Tests.Test.AutoCompletePageTest(Chrome).AutoCompletePage_FillCountryNameThenSelectCountry
System.IO.FileNotFoundException : Could not load file or assembly 'nunit.core.interfaces, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77' or one of its dependencies. The system cannot find the file specified.
```
@PatrykSzwer, wdyt, maybe i'm going to the wrong direction, and we can re-run tests somehow differently?

**Comment by warpech** [comment]
I guess in NUnit 3 you should use this API? https://github.com/nunit/docs/wiki/Test-Engine-API

**Comment by kegor** [comment]
I tried to use this updated API, but for now i'm getting:
```
NUnit.Engine.NUnitEngineException
  HResult=0x80131500
  Message=Failed to start remote test agent.
  Source=nunit.engine
  StackTrace:
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
```
during executing line with 
`var result = runner.Run(listener: null, filter: filter);` in VS debug and didn't find the answer yet.

**Comment by warpech** [comment]
UniformDocs is using `NUnit.ConsoleRunner.3.6.1`. This issue says that a similar problem was fixed in 3.9: https://github.com/nunit/nunit-console/issues/436

Maybe upgrade all packages to the current versions?

**Comment by warpech** [comment]
Reassigning this issue from Egor to me. I will see if I can finish the PR https://github.com/Starcounter/UniformDocs/pull/402
